version: "3.9"

services:
  keycloak:
    image: keycloak-preseed:poc                 # <-- your local image tag
    container_name: kc-poc
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: change_me
    command: start-dev --import-realm


  mongodb:
    image: mongo-preseed:poc                    # <-- your local image tag
    container_name: mongo-seeded
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: appdb
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ping:1}).ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      default:
        aliases:
          - mongo

  backend:
    image: vre_maturity_backend:poc                 # <-- your local image tag
    container_name: thesis-backend
    depends_on:
      mongodb:
        condition: service_healthy
    # Your Dockerfile EXPOSEs 3000; map it to 8081 on the host to avoid clashing with frontend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/vre_level?authSource=admin
      OIDC_ISSUER_URL: http://keycloak:8080/realms/vre
      OIDC_CLIENT_ID: app-frontend               # <-- must match your realm export
      OIDC_CLIENT_SECRET: change_me              # <-- match your client (if confidential)
      PUBLIC_FRONTEND_URL: http://localhost:4000
      NODE_ENV: docker

  frontend:
    image: vre_maturity_frontend:poc              # <-- your local image tag
    container_name: thesis-frontend
    depends_on:
      backend:
        condition: service_started
    # adjust the container port if your frontend serves on something else
    ports:
      - "4000:4000"
    environment:
      VITE_API_URL: http://localhost:8081
      VITE_OIDC_ISSUER: http://keycloak:8080/realms/vre
      VITE_OIDC_CLIENT_ID: app-frontend
      VITE_OIDC_REDIRECT_URI: http://localhost:3000/callback
      VITE_OIDC_LOGOUT_REDIRECT_URI: http://localhost:3000/
